#! /bin/bash

while read -r line
do
  echo "$line" |
        sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | \
        sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/'' | \
        sed ''/RUN/s//$(printf "\033[34mRUN\033[0m")/''
done < "${1:-/dev/stdin}"
